# Generated by Django 5.0.3 on 2024-12-06 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('github_username', models.CharField(max_length=100, unique=True)),
                ('avatar_url', models.URLField()),
                ('specialite', models.CharField(choices=[('frontend', 'Développeur Front-end'), ('backend', 'Développeur Back-end'), ('fullstack', 'Développeur Full-stack'), ('uiux', 'Designer UI/UX'), ('devops', 'Ingénieur DevOps'), ('data', 'Scientifique de Données'), ('pm', 'Chef de Projet')], default='fullstack', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Defis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_du_defis', models.CharField(max_length=200)),
                ('montant', models.IntegerField()),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defis', to='api.contributor')),
            ],
        ),
    ]
